name: Run Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.15'

      # Install uv and dependencies
      - name: Install dependencies using uv
        run: |
          pip install uv
          uv install

      # Run unittest discovery
      - name: Run tests
        run: uv run python -m unittest discover -s tests
